//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobblePedia.Models.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CobblePedia.Models.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability_{0}_Effect.
        /// </summary>
        internal static string AbilityKeyEffect {
            get {
                return ResourceManager.GetString("AbilityKeyEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability_{0}_Flavor.
        /// </summary>
        internal static string AbilityKeyFlavor {
            get {
                return ResourceManager.GetString("AbilityKeyFlavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability_{0}_Name.
        /// </summary>
        internal static string AbilityKeyName {
            get {
                return ResourceManager.GetString("AbilityKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EggGroup_{0}_Name.
        /// </summary>
        internal static string EggGroupKeyName {
            get {
                return ResourceManager.GetString("EggGroupKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP_{0}_Description.
        /// </summary>
        internal static string ExperienceGroupKeyDescription {
            get {
                return ResourceManager.GetString("ExperienceGroupKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gen{0}.
        /// </summary>
        internal static string GenerationId {
            get {
                return ResourceManager.GetString("GenerationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gen_{0}.
        /// </summary>
        internal static string GenerationKeyName {
            get {
                return ResourceManager.GetString("GenerationKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move_{0}_Effect.
        /// </summary>
        internal static string MoveKeyEffect {
            get {
                return ResourceManager.GetString("MoveKeyEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move_{0}_Flavor.
        /// </summary>
        internal static string MoveKeyFlavor {
            get {
                return ResourceManager.GetString("MoveKeyFlavor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move_{0}_Name.
        /// </summary>
        internal static string MoveKeyName {
            get {
                return ResourceManager.GetString("MoveKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species_{0}_Description.
        /// </summary>
        internal static string SpeciesKeyDescription {
            get {
                return ResourceManager.GetString("SpeciesKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species_{0}_Name.
        /// </summary>
        internal static string SpeciesKeyName {
            get {
                return ResourceManager.GetString("SpeciesKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer_{0}_Name.
        /// </summary>
        internal static string TrainerKeyName {
            get {
                return ResourceManager.GetString("TrainerKeyName", resourceCulture);
            }
        }
    }
}
