//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobblePedia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CobblePedia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/DamageClass/{0}.png.
        /// </summary>
        internal static string DamageClassPicture {
            get {
                return ResourceManager.GetString("DamageClassPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Eggs/Egg-{0}.png.
        /// </summary>
        internal static string EggGroupPicture {
            get {
                return ResourceManager.GetString("EggGroupPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Items/{0}.png.
        /// </summary>
        internal static string ItemPicture {
            get {
                return ResourceManager.GetString("ItemPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/MoveTarget/{0}.png.
        /// </summary>
        internal static string MoveTargetPicture {
            get {
                return ResourceManager.GetString("MoveTargetPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EggGroup_{0}.
        /// </summary>
        internal static string PokemonEggGroup {
            get {
                return ResourceManager.GetString("PokemonEggGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Physiques/Height-{0}.png.
        /// </summary>
        internal static string PokemonHeightPicture {
            get {
                return ResourceManager.GetString("PokemonHeightPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Pokemon/{0}.
        /// </summary>
        internal static string PokemonPicturePath {
            get {
                return ResourceManager.GetString("PokemonPicturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Physiques/Weight-{0}.png.
        /// </summary>
        internal static string PokemonWeightPicture {
            get {
                return ResourceManager.GetString("PokemonWeightPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer_Series_{0}.
        /// </summary>
        internal static string TrainerSeries {
            get {
                return ResourceManager.GetString("TrainerSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer_Type_{0}.
        /// </summary>
        internal static string TrainerType {
            get {
                return ResourceManager.GetString("TrainerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Types/{0}-Icon.png.
        /// </summary>
        internal static string TypeIconPath {
            get {
                return ResourceManager.GetString("TypeIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/Types/{0}.png.
        /// </summary>
        internal static string TypeLargeIconPath {
            get {
                return ResourceManager.GetString("TypeLargeIconPath", resourceCulture);
            }
        }
    }
}
